version: 2

# build:
#   os: 'ubuntu-22.04
#   tools:
#     python: '3.12'
#   commands:
#     - pip install sphinx_rtd_theme

# python:
#   install:
#     -requirements: docs/requirements.txt

# sphinx:
#   configuration: docs/source/conf.py

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

